# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DpPUeU0TRgEf3XW27hTO-Cp43UCUu7g6

# Proyek Analisis Data: bike sharing dataset
- **Nama:** Rey Aji Darusalam
- **Email:** reyaji21@if.unjani.ac.id
- **ID Dicoding:** N9ZOOQRJ6ZG5

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Bagaimana penggunaan layanan bike sharing berkaitan dengan faktor-faktor seperti musim, cuaca, dan waktu dalam sehari?
- Pertanyaan 2 : Bagaimana pola penggunnaan sepeda berubah seiring waktu, khususnya dalam kaitannya dengan musim dan hari libur

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

"""## Data Wrangling

### Gathering Data

Membaca file CSV menjadi DataFrame dan Menampilkan DataFrame hour_df
"""

hour_df = pd.read_csv("hour.csv")
hour_df.head()

"""Membaca file CSV menjadi DataFrame dan Menampilkan DataFrame day_df"""

day_df = pd.read_csv("day.csv")
day_df.head()

"""### Assessing Data

Menampilkan info terbaru dari day_df
"""

day_df.info()

"""Menampilkan info terbaru dari hour_df"""

hour_df.info()

"""Menampilkan data yang hilang (missing value) dari day_df"""

day_df.isna().sum()

"""Menampilkan data yang hilang (missing value) dari hour_df"""

hour_df.isna().sum()

"""Mengecek apakah ada duplikasi atau tidak pada day_df"""

print("Jumlah Duplikasi : ", day_df.duplicated().sum())

"""Mengecek apakah ada duplikasi atau tidak pada hour_df"""

print("Jumlah Duplikasi : ", hour_df.duplicated().sum())

"""Menampilakn ringkasan statistik deskriptif dari day_df"""

day_df.describe()

"""Menampilakn ringkasan statistik deskriptif dari hour_df"""

hour_df.describe()

"""### Cleaning Data"""

hour_df.drop_duplicates(inplace=True)
hour_df.dropna(inplace=True)
hour_df['dteday'] = pd.to_datetime(hour_df['dteday'])
hour_df.head()

"""## Exploratory Data Analysis (EDA)

Data Statistik Harian
"""

day_df.describe(include="all")

"""Penggunaan Layanan Bike-Sharing pada hari kerja dan hari libur"""

day_df.describe(include="all")
day_df.groupby(by=["workingday", "weekday"]).agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

"""Penggunaan Layanan Bike Sharing Berdasarkan Musim dan Tanggal"""

day_df.groupby(by=["season", "dteday"]).agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})

""" Menggabungkan data berdasarkan musim dan tanggal, kemudian menghitung total penggunaan layanan bike sharing untuk pengguna casual, pengguna terdaftar, dan total pengguna"""

usage_by_season_date = day_df.groupby(by=["season", "dteday"]).agg({
    "casual": "sum",
    "registered": "sum",
    "cnt": "sum"
})
usage_by_season_date.head()

"""Mendistribusikan suhu menggunakan histogram"""

st.write(hour_df.describe())

plt.figure(figsize=(10,6))
sns.histplot(data=hour_df, x='temp', bins=30, kde=True)
plt.title('Distribusi Suhu')
plt.xlabel('Suhu(Celsius)')
plt.ylabel('Frekuensi')
plt.show()

"""### Explore ...

Korelasi antara suhu dan penyewa sepeda
"""

plt.figure(figsize=(10,6))
sns.scatterplot(data=hour_df, x='temp', y='cnt')
plt.title('Hubungan Suhu dan Sewa Sepeda')
plt.xlabel('Suhu(Celsius)')
plt.ylabel('Jumlah Sewa Sepeda')
plt.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Melihat pola apakah ada korelasi antara suhu dan jumlah sewa sepeda.
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=hour_df, x='weathersit', y='cnt')
plt.title('Pengaruh Cuaca terhadap Jumlah Sewa Sepeda')
plt.xlabel('Cuaca')
plt.ylabel('Jumlah Sewa Sepeda')
plt.show()

"""### Pertanyaan 2: Melihat hubungan antara pengguna sepeda dengan penggunaan sepeda."""

plt.figure(figsize=(12, 6))
sns.lineplot(data=day_df, x='dteday', y='cnt')
plt.title('Pola Penggunaan Sepeda per Hari')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah Sewa Sepeda')
plt.xticks(rotation=45)
plt.show()

"""## Conclusion

- Conclution pertanyaan 1 : Berdasarkan analisis, terbukti bahwa cuaca mempunyai pendekatan yang penting dalam mengurangi jumlah limbah sepeda. Sebaliknya, cuaca cerah cenderung meningkatkan jumlah limbah, karena buruk cenderung memiliki jumlah limbah yang lebih rendah.
- Conclution pertanyaan 2 : Penggunaan sepeda menghasilkan kontraksi otot yang jelas, dengan puncak kontraksi yang lebih tinggi pada saat puncak kontraksi otot dan kontraksi puncak yang lebih rendah pada saat puncak kontraksi otot. Selain itu, terdapat fluktuasi harian yang menunjukkan bagaimana karyawan menggunakan sistem selama minggu kerja dan akhir pekan, dengan tingkat penggunaan yang lebih tinggi pada hari kerja.
"""